### ISSUE TITLE
Problem install opencv4nodejs

### ISSUE THREAD

**Issue by LinuxTux193** [bloodyev/tiktok-register#7]
I have a problem installing opencv4nodejs, here the error: 
`
npm ERR! Error: no OpenCV libraries found in lib dir: /usr/lib/x86_64-linux-gnu/cmake/opencv4
npm ERR!     at Object.<anonymous> (/home/linux/Programmazione/tiktok-register/node_modules/opencv4nodejs/install/install.js:45:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:827:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47
npm ERR! 
npm ERR! Node.js v18.3.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linux/.npm/_logs/2022-08-30T15_15_37_025Z-debug-0.log

`
What is the problem?

**Comment by bloodyev** [comment]
> I have a problem installing opencv4nodejs, here the error:
> 
> ```
> npm ERR! Error: no OpenCV libraries found in lib dir: /usr/lib/x86_64-linux-gnu/cmake/opencv4
> npm ERR!     at Object.<anonymous> (/home/linux/Programmazione/tiktok-register/node_modules/opencv4nodejs/install/install.js:45:9)
> npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
> npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
> npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
> npm ERR!     at Module._load (node:internal/modules/cjs/loader:827:12)
> npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
> npm ERR!     at node:internal/main/run_main_module:17:47
> npm ERR! 
> npm ERR! Node.js v18.3.0
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/linux/.npm/_logs/2022-08-30T15_15_37_025Z-debug-0.log
> ```
> 
> What is the problem?

npm i opencv4nodejs

**Comment by LinuxTux193** [comment]
> > I have a problem installing opencv4nodejs, here the error:
> > ```
> > npm ERR! Error: no OpenCV libraries found in lib dir: /usr/lib/x86_64-linux-gnu/cmake/opencv4
> > npm ERR!     at Object.<anonymous> (/home/linux/Programmazione/tiktok-register/node_modules/opencv4nodejs/install/install.js:45:9)
> > npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
> > npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
> > npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
> > npm ERR!     at Module._load (node:internal/modules/cjs/loader:827:12)
> > npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
> > npm ERR!     at node:internal/main/run_main_module:17:47
> > npm ERR! 
> > npm ERR! Node.js v18.3.0
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /home/linux/.npm/_logs/2022-08-30T15_15_37_025Z-debug-0.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What is the problem?
> 
> npm i opencv4nodejs

do you think i'm stupid?
